/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethods */

#ifndef _Included_NativeMethods
#define _Included_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMethods
 * Method:    GetFolder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMethods_GetFolder
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
